---

#- yum: name={{ item }}
#  with_items:
#    - epel-release
#
#- yum: name={{ item }}
#  with_items:
#    - munin-node

- copy: src=./{{ item }} dest=/etc/munin/{{ item }}
  with_items:
    - munin-node.conf
  notify:
    - munin-node restart

- service: name=munin-node state=started enabled=yes

- name: munin-node check
  shell: echo "fetch load" | nc localhost 4949
  changed_when: no
