---

#- yum: name={{ item }}
#  with_items:
#    - epel-release
#
#- yum: name={{ item }}
#  with_items:
#    - httpd
#    - munin
#    - munin-cgi
#    - net-snmp-utils

- copy: src=./{{ item }} dest=/etc/munin/{{ item }}
  with_items:
    - munin.conf
    - munin-node.conf
    - conf.d/example.conf
    - plugin-conf.d/zzz-snmp
  notify:
    - munin-node restart

- stat: path=/etc/munin/munin-htpasswd
  register: res
  changed_when: res.stat.size == 0

- name: munin-htpasswd generate
  shell: htpasswd -bc /etc/munin/munin-htpasswd munin pass
  when: res|changed

- stat: path=/etc/munin/plugins/entropy
  register: res
  changed_when: res.stat.exists

- shell: rm -f /etc/munin/plugins/*
  when: res|changed
  notify:
    - munin-node restart

- file: src={{ item.value }} dest=/etc/munin/plugins/{{ item.key }} state=link
  with_dict:
    cpu: /usr/share/munin/plugins/cpu
    df: /usr/share/munin/plugins/df
    diskstats: /usr/share/munin/plugins/diskstats
  notify:
    - munin-node restart

#- name: munin snmp plugin check
#  shell: |
#    munin-node-configure --snmp 192.168.33.10 --snmpcommunity oreore --shell
#  register: res
#  always_run: yes
#  changed_when: res.stdout|length

#- name: munin snmp plugin install
#  shell: |
#    munin-node-configure --snmp 192.168.33.10 --snmpcommunity oreore --shell | bash -x
#  when: res|changed

- stat: path=/etc/munin/munstrap/templates/
  register: res
  changed_when: not res.stat.exists

- name: download munin-contrib munstrap
  shell: |
    set -eux
    rm -fr /tmp/munin-contrib
    mkdir -p /tmp/munin-contrib
    mkdir -p /etc/munin/munstrap
    wget https://github.com/munin-monitoring/contrib/archive/master.tar.gz -O - |
      tar xzf - -C /tmp/munin-contrib --strip-components=1
    rm -fr /var/www/html/munin/static
    rsync -av /tmp/munin-contrib/templates/munstrap/static/    /etc/munin/munstrap/static/
    rsync -av /tmp/munin-contrib/templates/munstrap/templates/ /etc/munin/munstrap/templates/
    rm -fr /tmp/munin-contrib
  when: res|changed

- service: name=munin-node state=started enabled=yes

- name: munin-node check
  shell: echo "fetch load" | nc localhost 4949
  changed_when: no

- service: name=httpd state=started enabled=yes
