---

- yum: name={{ item }}
  with_items:
    - epel-release

- yum: name={{ item }}
  with_items:
    - munin
    - net-snmp-utils

- copy: src=./{{ item }} dest=/{{ item }}
  with_items:
    - /etc/munin/munin.conf
    - /etc/munin/munin-node.conf
    - /etc/munin/conf.d/example.conf
    - /etc/munin/plugin-conf.d/zzz-snmp
    - /etc/munin/plugin-conf.d/zzz-ping
  notify:
    - munin-node restart

- template: src={{ item }} dest=//etc/munin/conf.d/
  with_items:
    - contact.conf
  notify:
    - munin-node restart

- name: munin snmp plugin check
  shell: |
    munin-node-configure --snmp 192.168.33.10 --snmpcommunity oreore --shell
  register: res
  always_run: yes
  changed_when: res.stdout|length

- name: munin snmp plugin install
  shell: |
    munin-node-configure --snmp 192.168.33.10 --snmpcommunity oreore --shell | bash -x
  when: res|changed

# manual プラグイン
- file: src={{ item.src }} path=/etc/munin/plugins/{{ item.dest }} state=link
  with_items:
    - { src: /usr/share/munin/plugins/ping_, dest: ping_192.168.33.10 }
    - { src: /usr/share/munin/plugins/ping_, dest: ping_192.168.33.11 }
    - { src: /usr/share/munin/plugins/ping_, dest: ping_192.168.33.12 }

- stat: path=/etc/munin/contrib/munstrap/templates/
  register: res
  changed_when: not res.stat.exists

- name: download munin-contrib munstrap
  shell: |
    set -eux
    rm -fr /tmp/munin-contrib
    mkdir -p /tmp/munin-contrib
    mkdir -p /etc/munin/contrib/munstrap
    wget https://github.com/munin-monitoring/contrib/archive/master.tar.gz -O - |
      tar xzf - -C /tmp/munin-contrib --strip-components=1
    rm -fr /var/www/html/munin/static
    rsync -av /tmp/munin-contrib/templates/munstrap/static/    /etc/munin/contrib/munstrap/static/
    rsync -av /tmp/munin-contrib/templates/munstrap/templates/ /etc/munin/contrib/munstrap/templates/
    rm -fr /tmp/munin-contrib
  when: res|changed

- service: name=munin-node       state=started enabled=yes
- service: name=munin-fcgi-graph state=started enabled=yes
- service: name=munin-fcgi-html  state=started enabled=yes

- name: munin-node check
  shell: echo "fetch load" | nc localhost 4949
  changed_when: no
